/**
 * Response trailers, and the ordering the fetch spec requires of them.
 *
 * Trailers only exist once a body has ended, so `response.trailers` does not resolve
 * until the body has been consumed — see https://github.com/whatwg/fetch/pull/1940.
 * That makes "await trailers, then read the body" a deadlock the caller wrote, which
 * is why the pending case is asserted here rather than smoothed over: the promise has
 * to stay cheap and cancellable while it waits, and it has to resolve the moment the
 * body ends.
 */

const test = require("tape");
const http = require("node:http");

const { Agent } = require("../index.js");
const { fetch } = require("../wrapper.js");

const PAYLOAD = "trailers-payload";
const TRAILER = "x-checksum";
const VALUE = "abc123";

/**
 * `/trailers` sends one, `/plain` sends none.
 *
 * Cleartext HTTP/1.1 deliberately: trailers have nothing to do with TLS, and the
 * shared test CA is generated by whichever openssl the platform ships -- which is a
 * source of failures of its own, since rustls rejected that certificate for its
 * extended key usage on macOS and Windows while accepting it on Linux. An OS-assigned
 * port, since there is no UDP listener to coordinate with here.
 */
async function origin() {
	const sockets = new Set();
	const server = http.createServer((req, res) => {
		res.setHeader("content-type", "text/plain");
		if (req.url === "/trailers") {
			res.setHeader("trailer", TRAILER);
			res.write(PAYLOAD);
			res.addTrailers({ [TRAILER]: VALUE });
			res.end();
			return;
		}
		res.end(PAYLOAD);
	});
	server.on("connection", (socket) => {
		sockets.add(socket);
		socket.on("close", () => sockets.delete(socket));
	});

	await new Promise((resolve, reject) => {
		server.once("error", reject);
		server.listen(0, "127.0.0.1", resolve);
	});

	return {
		url: `http://127.0.0.1:${server.address().port}`,
		agent: new Agent(),
		close: () =>
			new Promise((resolve) => {
				// The agent pools its connection, so a bare close() never settles.
				for (const socket of sockets) socket.destroy();
				sockets.clear();
				server.close(resolve);
				setTimeout(resolve, 500).unref();
			}),
	};
}

test("trailers: arrive once the body has been read", async (t) => {
	const server = await origin();
	try {
		const res = await fetch(`${server.url}/trailers`, { agent: server.agent, timeout: 10000 });
		t.equal(await res.text(), PAYLOAD, "the body reads back");

		const trailers = await res.trailers;
		t.ok(trailers, "and the trailers resolve");
		t.equal(trailers.get(TRAILER), VALUE, "carrying what the server sent");
	} finally {
		await server.close();
		t.end();
	}
});

test("trailers: a body with none resolves to null", async (t) => {
	const server = await origin();
	try {
		const res = await fetch(`${server.url}/plain`, { agent: server.agent, timeout: 10000 });
		await res.text();
		t.equal(
			await res.trailers,
			null,
			"null rather than an empty Headers, so a caller can tell none arrived",
		);
	} finally {
		await server.close();
		t.end();
	}
});

test("trailers: pending until the body is consumed, and idle while pending", async (t) => {
	const server = await origin();
	try {
		const res = await fetch(`${server.url}/trailers`, { agent: server.agent, timeout: 10000 });

		// Held, not awaited: awaiting here is the deadlock the spec describes.
		const pending = res.trailers;

		const before = process.cpuUsage();
		const raced = await Promise.race([
			pending.then(() => "resolved"),
			new Promise((resolve) => setTimeout(() => resolve("pending"), 500)),
		]);
		const spentMs = (process.cpuUsage(before).user + process.cpuUsage(before).system) / 1000;

		t.equal(raced, "pending", "does not resolve before the body is consumed, per the spec");
		// The bug this replaces was a `yield_now` loop: half a second of waiting cost half
		// a second of CPU, kept Node's event loop alive, and survived a test timeout. A
		// parked future spends about a millisecond, so the threshold is loose on purpose:
		// it only has to sit well under the ~500ms a spin costs, and stay clear of what a
		// slow or noisy runner might attribute to this process.
		t.ok(
			spentMs < 200,
			`waiting is idle, not a spin: ${spentMs.toFixed(0)}ms of CPU across 500ms of waiting`,
		);

		// And the same promise settles as soon as the body ends.
		t.equal(await res.text(), PAYLOAD, "the body is still there to read");
		const trailers = await pending;
		t.equal(
			trailers && trailers.get(TRAILER),
			VALUE,
			"the promise held from before the read resolves once the body ends",
		);
	} finally {
		await server.close();
		t.end();
	}
});

test("trailers: a discarded body settles them as none", async (t) => {
	const server = await origin();
	try {
		const res = await fetch(`${server.url}/trailers`, { agent: server.agent, timeout: 10000 });

		// Held first, so this also covers the case that used to wedge: a waiter already
		// parked when the body gets thrown away.
		const pending = res.trailers;
		await res.discard();

		t.equal(
			await pending,
			null,
			"discarding the body discards its trailers, rather than waiting for trailers " +
				"that can no longer arrive",
		);
		t.equal(await res.trailers, null, "and asking again says the same thing");
	} finally {
		await server.close();
		t.end();
	}
});
