/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The `Agent` interface of the Faith API represents an instance of an HTTP client. Each `Agent` has
 * its own options, connection pool, caches, etc. There are also conveniences such as `headers` for
 * setting default headers on all requests done with the agent, and statistics collected by the agent.
 *
 * Re-using connections between requests is a significant performance improvement: not only because
 * the TCP and TLS handshake is only performed once across many different requests, but also because
 * the DNS lookup doesn't need to occur for subsequent requests on the same connection. Depending on
 * DNS technology (DoH and DoT add a whole separate handshake to the process) and overall latency,
 * this can not only speed up requests on average, but also reduce system load.
 *
 * For this reason, and also because in browsers this behaviour is standard, **all** requests with
 * Faith use an `Agent`. For `fetch()` calls that don't specify one explicitly, a global agent with
 * default options is created on first use.
 *
 * There are a lot more options that could be exposed here; if you want one, open an issue.
 */
export declare class Agent {
  constructor(options?: AgentOptions | undefined | null)
  /**
   * Close the agent, releasing its connection pool, DNS resolver, and any
   * background tasks it owns, rather than waiting for the garbage collector
   * to drop it. This is worth doing when you create many short-lived agents;
   * a single long-lived agent can just be left to the GC.
   *
   * Requests already in flight run to completion. Any new request on a closed
   * agent throws a `Closed` error. Calling `close()` more than once is a
   * no-op. The cookie store, if any, remains readable via `getCookie`.
   */
  close(): void
  /**
   * Tell the agent the network underneath it has changed, so it stops deciding from what it
   * learned about a network that is gone.
   *
   * Node has no portable signal for an interface or connectivity change, so Faith cannot
   * detect one; this is the reaction, and wiring it to a trigger (an OS notification, a VPN
   * transition, a captive-portal sign-in) is the caller's own. It drops pooled connections,
   * flushes the DNS cache, demotes the HTTP/3 origins that a real response confirmed back to
   * advertised so a background probe re-verifies them, and clears the HTTP/3 failure and slow
   * states, their cooldown backoff, and the path-time averages.
   *
   * Configuration, `http3.hints`, `Alt-Svc` advertisements, the cookie jar, the HTTP cache and
   * the `stats()` counters are all kept: none of them is a claim about a network path.
   *
   * Requests already in flight are not interrupted and run to completion on the connections
   * they hold; the reset shapes what requests started afterwards draw on. Calling it on a
   * closed agent does nothing, and calling it repeatedly is harmless.
   *
   * spec:NETCHG
   */
  networkChanged(): void
  /**
   * Add a cookie into the agent.
   *
   * The cookie goes through the same rules a `Set-Cookie` header would, with the url supplying
   * the scheme and host they read, so this does nothing if:
   * - the cookie store is disabled
   * - the url is malformed
   * - the cookie does not parse
   * - a `__Host-` or `__Secure-` name prefix is not satisfied
   * - the cookie is larger than `cookies.maxSize`
   */
  addCookie(url: string, cookie: string): void
  /**
   * Retrieve a cookie from the store.
   *
   * Returns `null` if:
   * - there's no cookie at this url
   * - the cookie store is disabled
   * - the url is malformed
   * - the cookie cannot be represented as a string
   */
  getCookie(url: string): string | null
  /**
   * Returns statistics gathered by this agent:
   *
   * - `requestsSent`
   * - `responsesReceived`
   * - `bodiesStarted`
   * - `bodiesFinished`
   */
  stats(): AgentStats
  /**
   * Returns information on current connections open by this agent.
   *
   * Only tracks TCP connections currently (upstream limitation). Stats are updated once a second:
   * this makes it possible to track indicators over time to find the retransmission rate, for
   * example. The `lostPackets` and `deliveryRateBps` stats are only available on Linux. Some other
   * fields might also be missing depending on platform support; and no forward guarantees are made
   * on field availability. If the platform isn't supported at all, this will always return empty.
   */
  connections(): Array<ConnectionInfo>
  /**
   * Returns the DNS servers this agent resolves through, in the order they are queried, so
   * "are my lookups actually encrypted" is answerable from inside the process.
   *
   * Each entry gives the server's address, the transport in use (`udp`, `tcp`, `tls`, `https`,
   * `quic`, or `h3`), and how that transport was arrived at (`configured` or `conventional`).
   * The list is empty until the resolver has been used, because it reads its configuration on
   * first use, and empty for an agent using the system resolver. (spec:OBS#resolvers)
   */
  resolvers(): Array<ResolverInfo>
  /**
   * Warm the DNS cache for `host`, so a later request to it skips the lookup.
   *
   * Mirrors the browser's `dns-prefetch` resource hint. The argument is a bare host; a scheme,
   * port, or path in a fuller string is ignored. The returned promise resolves when the answer
   * lands in the cache and never rejects, whatever happens on the network — a resolution failure
   * resolves quietly, because the work is advisory. Under the system resolver there is no cache
   * to warm, so the call resolves without doing anything. A malformed host throws synchronously,
   * as does a call on a closed agent. (spec:WARM)
   */
  prefetchDns(host: string): Promise<undefined>
  /**
   * Open a pooled connection to `origin`, so the first request to it skips DNS, TCP, and TLS
   * setup.
   *
   * Mirrors the browser's `preconnect` resource hint. The argument is an origin
   * (`scheme://host[:port]`); a longer URL is reduced to its origin. The warm-up sends a
   * synthetic `HEAD` to the origin's root — the origin sees it — over the transport the next
   * foreground request would use: a confirmed HTTP/3 origin gets a warm QUIC connection, every
   * other origin a TCP one. The returned promise resolves when the attempt finishes and never
   * rejects: every network failure resolves quietly. A malformed origin throws synchronously, as
   * does a call on a closed agent. (spec:WARM)
   */
  preconnect(origin: string): Promise<undefined>
}

export declare class AgentStats {
  requestsSent: number
  responsesReceived: number
  /**
   * Number of response body streams that have been started (converted from raw body to stream).
   * This happens when `.body`, `.text()`, `.json()`, `.bytes()`, or similar methods are called.
   */
  bodiesStarted: number
  /**
   * Number of response body streams that have been fully consumed.
   * When `bodies_started - bodies_finished > 0`, there are bodies holding connections open.
   */
  bodiesFinished: number
}

/**
 * The `Response` interface of the Fetch API represents the response to a request.
 *
 * Faith does not allow its `Response` object to be constructed. If you need to, you may use the
 * `webResponse()` method to convert one into a Web API `Response` object; note the caveats.
 */
export declare class FaithResponse {
  /**
   * The `headers` read-only property of the `Response` interface contains the `Headers` object
   * associated with the response.
   *
   * Note that Faith does not provide a custom `Headers` class; instead the Web API `Headers` structure
   * is used directly and constructed by Faith when needed.
   *
   * This is a function as an internal implementation detail and the wrapper makes it a property.
   */
  headers(): Array<[string, string]>
  /**
   * The `ok` read-only property of the `Response` interface contains a boolean stating whether the
   * response was successful (status in the range 200-299) or not.
   */
  get ok(): boolean
  /**
   * Custom to Faith.
   *
   * The `peer` read-only property of the `Response` interface contains an object with information about
   * the remote peer that sent this response:
   */
get peer(): { address?: string; certificate?: Buffer }
/**
 * The `redirected` read-only property of the `Response` interface indicates whether or not the
 * response is the result of a request you made which was redirected.
 *
 * Note that by the time you read this property, the redirect will already have happened, and you
 * cannot prevent it by aborting the fetch at this point.
 *
 * One caveat specific to Faith: with the agent's `http3.upgradeFollowAdvertisedPort`
 * enabled, HTTP/3 responses compare URLs ignoring the port, because the port
 * was rewritten to the advertised one and would otherwise register as a
 * redirect. A genuine redirect differing only in port therefore reads as
 * `false` on those responses.
 */
get redirected(): boolean
/**
 * The `status` read-only property of the `Response` interface contains the HTTP status codes of the
 * response. For example, 200 for success, 404 if the resource could not be found.
 *
 * A value is `0` is returned for a response whose `type` is `opaque`, `opaqueredirect`, or `error`.
 */
get status(): number
/**
 * The `statusText` read-only property of the `Response` interface contains the status message
 * corresponding to the HTTP status code in `Response.status`. For example, this would be `OK` for a
 * status code `200`, `Continue` for `100`, `Not Found` for `404`.
 *
 * Faith always returns the canonical status message for the code. In HTTP/1, servers can send
 * custom status text, but that text is not surfaced here; in HTTP/2 and HTTP/3, custom status
 * text is not supported at all. For status codes with no well-known message, this is an empty
 * string.
 */
get statusText(): string
/**
 * The `type` read-only property of the `Response` interface contains the type of the response. The
 * type determines whether scripts are able to access the response body and headers.
 *
 * In Faith, this is always set to `basic`.
 */
get type(): string
/**
 * The `url` read-only property of the `Response` interface contains the URL of the response. The
 * value of the `url` property will be the final URL obtained after any redirects.
 */
get url(): string
/**
 * The `version` read-only property of the `Response` interface contains the HTTP version of the
 * response. The value will be the final HTTP version after any redirects and protocol upgrades.
 *
 * This is custom to Faith.
 */
get version(): string
/**
 * The `bodyUsed` read-only property of the `Response` interface is a boolean value that indicates
 * whether the body has been read yet.
 *
 * In Faith, this indicates whether the body stream has ever been read from or canceled, as defined
 * [in the spec](https://streams.spec.whatwg.org/#is-readable-stream-disturbed). Note that accessing
 * the `.body` property counts as a read, even if you don't actually consume any bytes of content.
 */
get bodyUsed(): boolean
/**
 * The `body` read-only property of the `Response` interface is a `ReadableStream` of the body
 * contents, or `null` for any actual HTTP response that has no body, such as `HEAD` requests and
 * `204 No Content` responses.
 *
 * Note that browsers currently do not return `null` for those responses, but the spec requires
 * it. Faith chooses to respect the spec rather than the browsers in this case.
 *
 * An important consideration exists in conjunction with the connection pool: if you start the
 * body stream, this will hold the connection until the stream is fully consumed. If another
 * request is started during that time, and you don't have an available connection in the pool
 * for the host already, the new request will open one.
 *
 * Note that this is a function as an implementation detail; the wrapper makes it a property.
 */
body(): ReadableStream<Buffer> | null
/**
 * Discard the response body, releasing the connection back to the pool.
 *
 * This is useful when you don't need the body but want to ensure the connection
 * can be reused for subsequent requests. If you don't call this and don't consume
 * the body, the connection may be held open until the response is garbage collected.
 *
 * For HTTP/1, the remaining body is read and thrown away so the connection can go back
 * to the pool. For HTTP/2 and HTTP/3, the body is dropped instead, which cancels the
 * stream (RST_STREAM / STOP_SENDING) without affecting the multiplexed connection.
 *
 * Returns a promise that resolves when the body has been fully discarded.
 */
discard(): Promise<undefined>
/**
 * The `bytes()` method of the `Response` interface takes a `Response` stream and reads it to
 * completion. It returns a promise that resolves with a `Uint8Array`.
 *
 * In Faith, this returns a Node.js `Buffer`, which can be used as (and is a subclass of) a `Uint8Array`.
 */
bytes(): Promise<Buffer>
/**
 * The `text()` method of the `Response` interface takes a `Response` stream and reads it to
 * completion. It returns a promise that resolves with a `String`. The response is always decoded
 * using UTF-8; as per spec, invalid UTF-8 sequences are replaced with U+FFFD rather than
 * causing an error.
 */
text(): Promise<string>
/**
 * The `json()` method of the `Response` interface takes a `Response` stream and reads it to
 * completion. It returns a promise which resolves with the result of parsing the body text as
 * `JSON`.
 *
 * Note that despite the method being named `json()`, the result is not JSON but is instead the
 * result of taking JSON as input and parsing it to produce a JavaScript object.
 *
 * Further note that, at least in Faith, this method first reads the entire response body as bytes,
 * and then parses that as JSON. This can use up to double the amount of memory. If you need more
 * efficient access, consider handling the response body as a stream.
 */
json(): Promise<any>
/**
 * Custom to Faith.
 *
 * `toFile(path, options)` writes the response body to a file on disk, the bytes
 * travelling from the network to the filesystem inside Faith without crossing into
 * JavaScript. It is a whole-body read alongside `bytes()` and its siblings: the first
 * consumer wins, `bodyUsed` becomes true once the read begins, and `integrity` is
 * verified when set.
 *
 * Resolves to `{ path, bytesWritten }`, where `path` is the absolute filesystem path
 * written to and `bytesWritten` counts the bytes that landed there.
 *
 * `onProgress` is reported to as the bytes land, at most every
 * [`PROGRESS_INTERVAL`], with a final report once the last byte is written. The
 * wrapper takes it from the options object; it arrives here as its own argument
 * because a threadsafe function cannot be a field of a `#[napi(object)]`.
 *
 * The `file://` URL to path conversion and the `InvalidPath` rejection happen in the
 * wrapper, so this receives a resolved string path.
 *
 * spec:BODY#tofile
 */
toFile(path: string, options?: ToFileOptions | undefined | null, onProgress?: ((progress: ToFileProgress) => void) | undefined | null): Promise<ToFileResult>
/**
 * Custom to Faith.
 *
 * The measurements behind the `timing` property, which the wrapper turns into a
 * `PerformanceResourceTiming`.
 *
 * A resource timing entry describes a finished request, so this does not resolve until
 * the body has ended: by being read, by `discard()`, or by the collector draining one
 * that was abandoned. A response that cannot carry a body has ended already.
 *
 * Phases are milliseconds from the start of the request rather than absolute times, so
 * the wrapper can place them on the same clock as the platform's other performance
 * entries.
 *
 * This is an async fn as an internal implementation detail and the wrapper makes it a
 * property.
 *
 * spec:RESP#request-timing
 */
timing(): Promise<TimingBreakdown>
/**
 * The `trailers()` read-only property of the `Response` interface returns a promise that
 * resolves to either `null` or a `Headers` structure that contains the HTTP/2 or /3 trailing
 * headers.
 *
 * This was once in the spec as a getter but was removed as it wasn't implemented by any browser.
 *
 * Trailers only exist once the body has ended, so this does not resolve until the body
 * has been consumed — by `text()`, `bytes()`, `json()`, `blob()`, or reading the `body`
 * stream. Awaiting it first, on its own, waits forever: that is the behaviour the fetch
 * spec's trailers proposal describes (<https://github.com/whatwg/fetch/pull/1940>), not
 * a quirk of Faith. Holding the promise while something else reads the body is fine, and
 * costs nothing while it is pending.
 *
 * `discard()` counts as consuming the body but discards its trailers with it, so this
 * then resolves to `null` rather than waiting for trailers that can no longer arrive.
 *
 * This is an async fn as an internal implementation detail and the wrapper makes it a property.
 */
trailers(): Promise<Array<[string, string]> | null>
/**
 * The `clone()` method of the `Response` interface creates a clone of a response object, identical
 * in every way, but stored in a different variable.
 *
 * `clone()` throws an `Error` if the response body has already been used.
 *
 * (In-spec, this should throw a `TypeError`, but for technical reasons this is not possible with Faith.)
 */
clone(): FaithResponse
}

/**
 * A streaming body that can be passed to fetch().
 * Create one with createStreamBodyPair(), then use the returned sender to push chunks.
 */
export declare class StreamBody {

}

/**
 * A sender that allows JavaScript to push chunks into a Rust stream.
 * This bypasses NAPI-rs's buggy ReadableStream Reader by letting JS
 * drive the chunk delivery explicitly.
 */
export declare class StreamBodySender {
  /**
   * Push a chunk of data into the stream.
   * Returns true if the chunk was sent successfully, false if the receiver was dropped.
   */
  push(chunk: Buffer): Promise<boolean>
  /** Close the stream, signaling that no more chunks will be sent. */
  close(): void
}

/** Settings related to the HTTP cache. This is a nested object. */
export interface AgentCacheOptions {
  /**
   * Which cache store to use: either `disk` or `memory`.
   *
   * Default: none (cache disabled).
   */
  store?: CacheStore
  /**
   * If `cache.store: "memory"`, the maximum amount of items stored.
   *
   * Default: 10_000.
   */
  capacity?: number
  /**
   * Default cache mode. This is the same as [`FetchOptions.cache`](#fetchoptionscache), and is used if
   * no cache mode is set on a request.
   *
   * Default: `"default"`.
   */
  mode?: RequestCacheMode
  /**
   * If `cache.store: "disk"`, then this is the path at which the cache data is. Must be writeable.
   *
   * Required if `cache.store: "disk"`.
   */
  path?: string
  /**
   * If `true`, then the response is evaluated from a perspective of a shared cache (i.e. `private` is
   * not cacheable and `s-maxage` is respected). If `false`, then the response is evaluated from a
   * perspective of a single-user cache (i.e. `private` is cacheable and `s-maxage` is ignored).
   * `shared: true` is required for proxies and multi-user caches.
   *
   * Default: true.
   */
  shared?: boolean
}

/**
 * Limits the cookie store enforces, from RFC 6265bis. Each is a cap; a caller who needs more room
 * raises the number.
 *
 * The `__Host-` and `__Secure-` name prefix rules are what those prefixes mean, so they always
 * apply and are not settable here: a cookie that shouldn't carry them is named without one.
 */
export interface AgentCookieOptions {
  /**
   * How far ahead of receipt a cookie may expire, in seconds. A cookie asking for longer, via
   * `Max-Age` or `Expires`, has its expiry reduced to this; a shorter one is left alone and a
   * session cookie stays a session cookie.
   *
   * Default: 34_560_000 (400 days).
   */
  maxAge?: number
  /**
   * The largest cookie stored, as the combined length of its name and value in bytes. A larger
   * cookie is not stored.
   *
   * Default: 4096.
   */
  maxSize?: number
  /**
   * How many cookies are kept for any one domain, which is a cookie's `Domain` attribute when it
   * has one and the host that set it otherwise.
   *
   * Default: 180.
   */
  maxPerHost?: number
  /**
   * How many cookies are kept across the whole store, bounding a server that spreads cookies
   * across subdomains to escape `maxPerHost`.
   *
   * Default: 3000.
   */
  maxTotal?: number
}

/** Settings related to DNS. This is a nested object. */
export interface AgentDnsOptions {
  /**
   * Use the system's DNS (via `getaddrinfo` or equivalent) rather than Faith's own DNS client (based on
   * [Hickory]). If you experience issues with DNS where Faith does not work but e.g. curl or native
   * fetch does, this should be your first port of call.
   *
   * Enabling this also disables Happy Eyeballs (for IPv6 / IPv4 best-effort resolution), the in-memory
   * DNS cache, and may lead to worse performance even discounting the cache.
   *
   * Default: false.
   *
   * [Hickory]: https://hickory-dns.org/
   */
  system?: boolean
  /**
   * Override DNS resolution for specific domains. This takes effect even with `dns.system: true`.
   *
   * Will throw if addresses are in invalid formats. You may provide a port number as part of the
   * address, it will default to port 0 otherwise, which will select the conventional port for the
   * protocol in use (e.g. 80 for plaintext HTTP). If the URL passed to `fetch()` has an explicit port
   * number, that one will be used instead. Resolving a domain to an empty `addresses` array effectively
   * blocks that domain from this agent.
   *
   * Default: no overrides.
   */
  overrides?: Array<DnsOverride>
  /**
   * An ordered list of resolver URLs, each URL's scheme selecting the transport Faith speaks to
   * that resolver: `udp://` and `tcp://` for conventional DNS on port 53, `tls://` for DNS over
   * TLS on port 853, `https://` for DNS over HTTPS on port 443, `quic://` for DNS over QUIC on
   * port 853, and `h3://` for DNS over HTTP/3 on port 443. A port in the URL overrides the
   * conventional one, and the HTTP transports use `/dns-query` when the URL supplies no path.
   *
   * The encrypted transports always authenticate the resolver. A URL fragment names the
   * certificate to expect (`tls://1.1.1.1#cloudflare-dns.com`); a hostname host authenticates
   * against the hostname; a bare-IP host authenticates against the address itself.
   *
   * Servers are queried in order, a later one reached only once those before it fail. Setting
   * this replaces the system's servers, so no discovery runs. Throws if a URL is unparseable or
   * its scheme is not one of the above, and combining it with `dns.system` throws.
   *
   * Default: system discovery.
   */
  servers?: Array<string>
  /**
   * Bound name resolution across the whole server list, in milliseconds. Exhausting several dead
   * servers costs a single timeout rather than one per server.
   *
   * Default: 5000.
   */
  timeout?: number
  /**
   * Replace the system's search list, the domains appended to a name that is not fully
   * qualified. Independent of `dns.servers`.
   *
   * Default: the system's search list.
   */
  searchDomains?: Array<string>
  /**
   * How many dots a name must contain before it is tried as given, ahead of the search list.
   * Independent of `dns.servers`.
   *
   * Default: the system's setting.
   */
  ndots?: number
  /**
   * Turn hosts-file lookup on or off. When unset, follows the platform's own convention.
   *
   * Default: platform convention.
   */
  hostsFile?: boolean
  /**
   * Further domains to exempt from the configured or encrypted resolver, for the internal
   * suffixes a network uses. Added to the always-exempt `localhost`, `.local`, and the network's
   * own DNS suffix; a domain is exempt when it matches an entry exactly or is a subdomain of one.
   *
   * Default: no extra exemptions.
   */
  exemptDomains?: Array<string>
  /**
   * Serve an expired cache entry immediately and refresh it in the background, rather than making
   * the lookup wait for a fresh answer. A host's address changes rarely, so an expired answer is
   * almost always still correct, and a connect failure against one that has moved re-resolves and
   * attempts the request again.
   *
   * Set `false` for an agent that must never connect to an address it knows to be out of date: an
   * expired entry is discarded and the lookup blocks on a fresh answer.
   *
   * Default: true.
   */
  serveStale?: boolean
  /**
   * How far past expiry an answer may still be served, in milliseconds. An entry older than this
   * is discarded rather than served: an answer stale enough stops being evidence about where the
   * host is, and a refresh still failing after that long is the case where the address most likely
   * did change.
   *
   * Default: 3600000 (one hour).
   */
  maxStale?: number
}

/** Settings related to HTTP flow control, shared by HTTP/2 and HTTP/3. This is a nested object. */
export interface AgentFlowControlOptions {
  /**
   * Maximum bytes an origin may send on any one stream before it must wait for Faith to
   * acknowledge them, for HTTP/2 and HTTP/3 alike.
   *
   * Larger windows keep a high-latency link full, at the cost of buffering more per stream.
   * The default follows browser practice, and is deliberately at the conservative end of it:
   * a pooled server-side client can hold many connections across many origins, so
   * per-connection memory multiplies harder here than in a browser.
   *
   * Set `http2.streamWindow` or `http3.streamWindow` to tune one protocol against the other.
   *
   * Default: 6 MiB.
   */
  streamWindow?: number
  /**
   * Maximum bytes an origin may send across all streams of one connection before it must
   * wait for Faith to acknowledge them, for HTTP/2 and HTTP/3 alike.
   *
   * This is larger than `streamWindow` so concurrent streams on one connection share the
   * connection's headroom, while still bounding the worst-case buffering of a connection
   * carrying many concurrent requests.
   *
   * Set `http2.connectionWindow` or `http3.connectionWindow` to tune one protocol against
   * the other.
   *
   * Default: 15 MiB.
   */
  connectionWindow?: number
}

/** Settings related to HTTP/2. This is a nested object. */
export interface AgentHttp2Options {
  /**
   * Maximum bytes an origin may send on any one HTTP/2 stream before it must wait for
   * Faith to acknowledge them. Overrides `flowControl.streamWindow` for HTTP/2 only.
   *
   * Ignored when `adaptiveWindow` is on.
   *
   * Default: unset (`flowControl.streamWindow`, itself 6 MiB by default).
   */
  streamWindow?: number
  /**
   * Maximum bytes an origin may send across all streams of one HTTP/2 connection before it
   * must wait for Faith to acknowledge them. Overrides `flowControl.connectionWindow` for
   * HTTP/2 only.
   *
   * Ignored when `adaptiveWindow` is on.
   *
   * Default: unset (`flowControl.connectionWindow`, itself 15 MiB by default).
   */
  connectionWindow?: number
  /**
   * Replace HTTP/2's static windows with windows that start small and grow towards a
   * bandwidth-delay estimate sampled from connection pings, capped at 16 MiB.
   *
   * This is off by default, and turning it on is usually the wrong move. A fresh connection
   * opens at 64 KiB, 96 times below the static default, and doubles only when a ping sample
   * reaches two thirds of the current estimate — so it takes many round trips to ramp up and
   * carries *less* throughput than the static window for all but the largest transfers. It
   * also takes over both windows, so `streamWindow` and `connectionWindow` stop applying.
   *
   * Its one real advantage is memory: it holds a large window open only on connections that
   * demonstrably need one. Since it caps at 16 MiB anyway, a static window near that ceiling
   * buys the same throughput from the first byte.
   *
   * HTTP/3 is unaffected either way, and keeps whichever windows apply to it.
   *
   * Default: `false`.
   */
  adaptiveWindow?: boolean
}

/** Settings related to HTTP/3. This is a nested object. */
export interface AgentHttp3Options {
  /**
   * The congestion control algorithm. The default is `cubic`, which is the same used in TCP in the
   * Linux stack. It's fair for all traffic, but not the most optimal, especially for networks with
   * a lot of available bandwidth, high latency, or a lot of packet loss. Cubic reacts to packet loss by
   * dropping the speed by 30%, and takes a long time to recover. BBR instead tries to maximise
   * bandwidth use and optimises for round-trip time, while ignoring packet loss.
   *
   * In some networks, BBR can lead to pathological degradation of overall network conditions, by
   * flooding the network by up to **100 times** more retransmissions. This is fixed in BBRv2 and BBRv3,
   * but Faith (or rather its underlying QUIC library quinn, [does not implement those yet][2]).
   *
   * [2]: https://github.com/quinn-rs/quinn/issues/1254
   *
   * Default: `cubic`. Accepted values: `cubic`, `bbr1`.
   */
  congestion?: Http3Congestion
  /**
   * Maximum duration of inactivity to accept before timing out the connection, in seconds. Note that
   * this only sets the timeout on this side of the connection: the true idle timeout is the _minimum_
   * of this and the peer's own max idle timeout. While the underlying library has no limits, Faith
   * defines bounds for safety: minimum 1 second, maximum 2 minutes (120 seconds).
   *
   * Default: 30.
   */
  maxIdleTimeout?: number
  /**
   * Whether HTTP/3 upgrade via Alt-Svc is enabled. When enabled, the agent will track Alt-Svc
   * headers from responses and automatically upgrade subsequent requests to HTTP/3 when available.
   *
   * Default: true.
   */
  upgradeEnabled?: boolean
  /**
   * Whether advertised HTTP/3 endpoints are verified with a background probe
   * before any foreground request is routed to them.
   *
   * An `Alt-Svc` advertisement says the server listens on UDP; it cannot say
   * there is UDP connectivity between you and it. Without probing, the next
   * request after an advertisement attempts HTTP/3 inline, and on a silently
   * broken UDP path it stalls until the QUIC idle timeout or
   * `upgradeAttemptTimeout` before falling back to TCP — recurring once per
   * failure cooldown for as long as the path stays broken.
   *
   * With probing (the default), requests keep using TCP until a background
   * `HEAD /` over HTTP/3 has confirmed the path. The probe shares the
   * connection pool, so the first upgraded request rides the probe's warm
   * connection. A broken path costs one failed background request per
   * cooldown and no foreground latency at all.
   *
   * The probe is a synthetic request the server will see in its logs. Set
   * this to `false` to restore the inline upgrade if that is unacceptable
   * (per-request billing, easily-alarmed WAFs).
   *
   * `hints` are exempt either way: a hint is your own assertion, so the first
   * request to a hinted origin speaks HTTP/3 immediately, which is also what
   * makes h3-only origins (no TCP listener) work.
   *
   * Default: true.
   */
  upgradeProbe?: boolean
  /**
   * Ceiling on how long a background HTTP/3 probe may take before the origin
   * is treated as failed, in **milliseconds**.
   *
   * This bounds background work only — no foreground request ever waits on a
   * probe — so it can afford to be generous: a healthy handshake plus HEAD
   * completes in one or two round trips. Set to 0 to leave probes bounded
   * only by the QUIC idle timeout.
   *
   * Default: 5000 (5 seconds).
   */
  upgradeProbeTimeout?: number
  /**
   * Demote an origin off HTTP/3 when its QUIC path is provenly slower than
   * its TCP path by this factor. Set to 0 to disable path-time demotion.
   *
   * Faith keeps a per-origin moving average of time-to-response-headers for
   * each protocol family. HTTP/3 is preferred at parity and when moderately
   * slower — its advantages (no head-of-line blocking, connection migration)
   * pay off beyond the average — so this factor should stay well above 1.
   * Only a sustained gap acts: at least 8 samples on each side, and the QUIC
   * average must also exceed the TCP one by an absolute 10ms so LAN-fast
   * origins don't flap on noise.
   *
   * A demoted origin is not treated as broken: it re-enters through a
   * background probe after `upgradeSlowTtl`, asking whether the path has
   * improved at zero foreground cost.
   *
   * Default: 2.5.
   */
  upgradeSlowFactor?: number
  /**
   * How long (in seconds) a path-time demotion holds before the origin is
   * re-evaluated. See `upgradeSlowFactor`.
   *
   * Default: 600 (10 minutes).
   */
  upgradeSlowTtl?: number
  /**
   * How long (in seconds) to cache an Alt-Svc advertisement before the first HTTP/3 attempt.
   * This is overridden by the `ma` (max-age) parameter in the Alt-Svc header if present.
   *
   * Default: 86400 (24 hours).
   */
  upgradeAdvertisedTtl?: number
  /**
   * How long (in seconds) to cache a confirmed working HTTP/3 connection.
   *
   * Default: 86400 (24 hours).
   */
  upgradeConfirmedTtl?: number
  /**
   * How long (in seconds) a *first* failed HTTP/3 attempt blocks an origin. During this
   * time, no HTTP/3 upgrades will be attempted for the origin, even if the server sends
   * Alt-Svc headers.
   *
   * Each consecutive failure doubles the cooldown, up to `upgradeFailedMaxTtl`, so an
   * origin whose UDP path is blocked for good is retried less and less often instead of
   * forever at this interval. A confirmed HTTP/3 response ends the run.
   *
   * Default: 300 (5 minutes).
   */
  upgradeFailedTtl?: number
  /**
   * Ceiling (in seconds) on the cooldown that consecutive HTTP/3 failures double out of
   * `upgradeFailedTtl`.
   *
   * On the defaults an origin that keeps failing is blocked for 5 minutes, then 10, 20,
   * 40, and an hour thereafter. Set this at or below `upgradeFailedTtl` for a flat
   * cooldown that never backs off.
   *
   * Default: 3600 (1 hour).
   */
  upgradeFailedMaxTtl?: number
  /**
   * How many consecutive cancelled HTTP/3 attempts, within a 60-second window,
   * demote an origin back to TCP.
   *
   * Faith normally learns that HTTP/3 is broken from a failed attempt. A request
   * cancelled via `AbortSignal` never produces that signal, so without this an
   * origin whose UDP path breaks keeps being retried over HTTP/3 for as long as
   * the Alt-Svc entry lives. Cancellations are treated as weak evidence: only a
   * sustained run of them demotes the origin, and any successful HTTP/3 response
   * resets the count.
   *
   * Strikes must land within about a minute of each other to count towards a
   * run. A retry loop whose backoff exceeds that window never accumulates one,
   * so callers with a long backoff should set this to 1 for immediate demotion
   * on the first cancelled attempt.
   *
   * One fault neither this nor `upgradeAttemptTimeout` catches: a path that
   * carries small datagrams but drops full-size ones (an MTU blackhole, say).
   * Response headers still arrive, so the attempt resolves and every mechanism
   * here counts it a success — the transfer then stalls partway through the
   * body, where nothing is watching. `maxIdleTimeout` or the request's own
   * timeout is what ends such a request, and the origin stays on HTTP/3.
   *
   * Set to 0 to disable, so only real HTTP/3 errors demote an origin.
   *
   * Default: 3.
   */
  upgradeCancelStrikes?: number
  /**
   * Ceiling on how long an HTTP/3 attempt may take to resolve before it is
   * given up on and the request is retried over TCP, in **milliseconds**.
   *
   * Note the unit: the other `upgrade*` settings are in seconds, but this one
   * is in milliseconds to match the `timeout` settings, because useful values
   * are sub-second.
   *
   * This bounds the wait for response headers, not the response body, so a slow
   * body is unaffected.
   *
   * The default is high, but not unconditionally inert: `maxIdleTimeout` is
   * configurable up to 120 seconds, and above 60 seconds this deadline becomes
   * the effective ceiling. Even below that, "QUIC's own idle timeout fires
   * first" only holds while the connection is idle — a transfer still running
   * past this deadline keeps the connection active, so no idle timeout is
   * coming to end it.
   *
   * On expiry the request is retried over TCP, which means it is re-sent: a
   * timeout often means the server is still processing, so a slow
   * non-idempotent request (a POST, say) can end up delivered twice. Lowering
   * this value trades that double-submission risk for faster recovery when a
   * UDP path breaks. Anyone setting it low should confirm their slowest
   * legitimate time to response headers fits well inside the budget.
   *
   * Set to 0 to disable, so an HTTP/3 attempt is bounded only by the QUIC idle
   * timeout and the request's own timeout.
   *
   * Default: 60000 (60 seconds).
   */
  upgradeAttemptTimeout?: number
  /**
   * Connect to the port a server advertises HTTP/3 on, even when it differs from
   * the origin's own port. **This is not standards-compliant**; it is off by
   * default.
   *
   * An `Alt-Svc` advertisement names a network endpoint for the origin, so
   * honouring one correctly means connecting to that endpoint while still
   * sending the *origin's* authority. reqwest cannot express that — it derives
   * the HTTP/3 connect target from the request URI's authority (tracked
   * upstream as [reqwest#1138](https://github.com/seanmonstar/reqwest/issues/1138)).
   * So by default Faith does not upgrade at all when the advertised port
   * differs, rather than guessing that the origin's own port also speaks
   * HTTP/3.
   *
   * Setting this to `true` upgrades anyway, by rewriting the request's port to
   * the advertised one. That gets HTTP/3 working today against servers you
   * control, at the cost of three deviations you should be aware of:
   *
   * - The request's `Host`/`:authority` carries the advertised port instead of
   *   the origin's, which [RFC 7838](https://www.rfc-editor.org/rfc/rfc7838)
   *   forbids. Servers that route on authority may misroute or reject; servers
   *   that ignore it are unaffected.
   * - `response.url` reports the port actually connected to.
   * - `redirected` ignores port differences, since the rewritten port would
   *   otherwise look like a redirect on every request.
   *
   * TLS is unaffected: certificates are still validated against the origin's
   * hostname. Only the port changes.
   *
   * Default: `false`.
   */
  upgradeFollowAdvertisedPort?: boolean
  /**
   * Maximum number of origins to track in the Alt-Svc cache.
   *
   * Default: 10000.
   */
  upgradeCacheCapacity?: number
  /**
   * Hints for hosts that are known to support HTTP/3. These are added to the Alt-Svc cache
   * on agent initialization, so the first request to these hosts will attempt HTTP/3.
   */
  hints?: Array<Http3Hint>
  /**
   * Maximum bytes an origin may send on any one HTTP/3 stream before it must wait for
   * Faith to acknowledge them. Overrides `flowControl.streamWindow` for HTTP/3 only.
   *
   * Default: unset (`flowControl.streamWindow`, itself 6 MiB by default).
   */
  streamWindow?: number
  /**
   * Maximum bytes an origin may send across all streams of one HTTP/3 connection before it
   * must wait for Faith to acknowledge them. Overrides `flowControl.connectionWindow` for
   * HTTP/3 only.
   *
   * Default: unset (`flowControl.connectionWindow`, itself 15 MiB by default).
   */
  connectionWindow?: number
  /**
   * Maximum bytes Faith transmits to an origin without acknowledgement, bounding upload
   * throughput the way the receive windows bound download. The origin's own flow control
   * applies on top of this, so it is a ceiling rather than a grant.
   *
   * This has no HTTP/2 counterpart: HTTP/2's send side is governed entirely by the window
   * the peer advertises, with no local cap to set.
   *
   * Default: 10 MB (quinn's own default).
   */
  sendWindow?: number
}

export interface AgentOptions {
  /** Settings related to the HTTP cache. This is a nested object. */
  cache?: AgentCacheOptions
  /**
   * Enable a persistent cookie store for the agent. Cookies received in responses will be preserved and
   * included in additional requests.
   *
   * `true` enables the store with the default limits; an options object enables it and tunes them,
   * so `{}` means the same as `true`.
   *
   * Default: `false`.
   *
   * You may use `agent.getCookie(url: string)` and `agent.addCookie(url: string, value: string)` to add
   * and retrieve cookies from the store.
   */
  cookies?: boolean | AgentCookieOptions
  /** Settings related to DNS. This is a nested object. */
  dns?: AgentDnsOptions
  /**
   * Flow-control windows shared by HTTP/2 and HTTP/3. This is a nested object.
   *
   * Setting these is the normal way to tune windows: one value applies to whichever protocol
   * a request negotiates, so throughput doesn't change when an origin upgrades from one to
   * the other. The `http2` and `http3` groups override them per protocol.
   */
  flowControl?: AgentFlowControlOptions
  /**
   * Sets the default headers for every request.
   *
   * If header names or values are invalid, they are silently omitted.
   * Sensitive headers (e.g. `Authorization`) should be marked.
   *
   * Default: none.
   */
  headers?: Array<Header>
  /** Settings related to HTTP/2. This is a nested object. */
  http2?: AgentHttp2Options
  /** Settings related to HTTP/3. This is a nested object. */
  http3?: AgentHttp3Options
  /**
   * Bind outgoing sockets to this local IP address before connecting.
   *
   * This also selects the address family of the HTTP/3 (QUIC) socket. By default that
   * socket binds the IPv6 wildcard (`[::]`), which fails on hosts without usable IPv6 —
   * there, HTTP/3 silently falls back to TCP. Faith detects that case automatically and
   * binds `0.0.0.0` instead, so you normally don't need to set this; provide it only to
   * force a specific source address. Throws if the value does not parse as an IP address.
   *
   * Default: unset (IPv6 wildcard for QUIC where available, else `0.0.0.0`).
   */
  localAddress?: string
  /** Settings related to the connection pool. This is a nested object. */
  pool?: AgentPoolOptions
  /** Switches that depart from standard behaviour on purpose. This is a nested object. */
  quirks?: AgentQuirksOptions
  /** Determines the behavior in case the server replies with a redirect status. */
  redirect?: Redirect
  /** Timeouts for requests made with this agent. This is a nested object. */
  timeout?: AgentTimeoutOptions
  /** Settings related to the connection pool. This is a nested object. */
  tls?: AgentTlsOptions
  /**
   * Custom user agent string.
   *
   * Default: `Faith/{version} reqwest/{version}`.
   */
  userAgent?: string
}

/** Settings related to the connection pool. This is a nested object. */
export interface AgentPoolOptions {
  /**
   * How many seconds of inactivity before a connection is closed.
   *
   * Default: 90 seconds.
   */
  idleTimeout?: number
  /**
   * The maximum amount of idle connections per host to allow in the pool. Connections will be closed
   * to keep the idle connections (per host) under that number.
   *
   * Default: `null` (no limit).
   */
  maxIdlePerHost?: number
}

/**
 * Switches that depart from standard behaviour on purpose. This is a nested object.
 *
 * Each quirk turns off a rule Faith otherwise upholds, in exchange for a capability the rule
 * forbids. All of them are off by default, so an agent constructed with no options is
 * standards-compliant. A quirk is for a caller who controls the origin, or has otherwise
 * established that what the rule guards against does not apply to them: turning one on means
 * requests may fail against origins that expect the standard behaviour.
 */
export interface AgentQuirksOptions {
  /**
   * Allow a streaming request body to be sent over an HTTP/1.x connection.
   *
   * The fetch standard reserves streaming request bodies for HTTP/2 and HTTP/3: a body read
   * from a `ReadableStream` has no known length when the headers go out, and an HTTP/1.x
   * origin or an intermediary on the path may refuse it. With this on, such a body sends over
   * whichever protocol the connection negotiates.
   *
   * Default: false.
   */
  h1RequestStreaming?: boolean
}

/** Timeouts for requests made with this agent. This is a nested object. */
export interface AgentTimeoutOptions {
  /**
   * Set a timeout for only the connect phase, in milliseconds.
   *
   * Default: none.
   */
  connect?: number
  /**
   * Set a timeout for read operations, in milliseconds.
   *
   * The timeout applies to each read operation, and resets after a successful read. This is more
   * appropriate for detecting stalled connections when the size isn't known beforehand.
   *
   * Default: none.
   */
  read?: number
  /**
   * Set a timeout for the entire request-response cycle, in milliseconds.
   *
   * The timeout applies from when the request starts connecting until the response body has finished.
   * Also considered a total deadline.
   *
   * Default: none.
   */
  total?: number
}

/** Settings related to the connection pool. This is a nested object. */
export interface AgentTlsOptions {
  /**
   * Enable TLS 1.3 Early Data. Early data is an optimisation where the client sends the first packet
   * of application data alongside the opening packet of the TLS handshake. That can enable the server
   * to answer faster, improving latency by up to one round-trip. However, Early Data has significant
   * security implications: it's vulnerable to replay attacks and has weaker forward secrecy. It should
   * really only be used for static assets or to squeeze out the last drop of performance for endpoints
   * that are replay-safe.
   *
   * Default: false.
   */
  earlyData?: boolean
  /**
   * Provide a PEM-formatted certificate and private key to present as a TLS client certificate (also
   * called mutual TLS or mTLS) authentication.
   *
   * The input should contain a PEM encoded private key and at least one PEM encoded certificate. The
   * private key must be in RSA, SEC1 Elliptic Curve or PKCS#8 format. This is one of the few options
   * that will cause the `Agent` constructor to throw if the input is in the wrong format.
   */
  identity?: Buffer | string
  /**
   * Disables plain-text HTTP.
   *
   * Default: false.
   */
  required?: boolean
  /**
   * Additional PEM-formatted root certificates to trust, on top of the platform's
   * trust store. Each entry may be a PEM bundle containing multiple certificates.
   *
   * This is mainly useful for connecting to servers with self-signed or private-CA
   * certificates, such as internal services or local test servers. This is one of the
   * few options that will cause the `Agent` constructor to throw if the input is in
   * the wrong format.
   */
  extraRoots?: Array<Buffer | string>
}

/**
 * The cache mode you want to use for the request. This may be any one of the following values:
 *
 * - `default`: The client looks in its HTTP cache for a response matching the request.
 *   - If there is a match and it is fresh, it will be returned from the cache.
 *   - If there is a match but it is stale, the client will make a conditional request to the remote
 *     server. If the server indicates that the resource has not changed, it will be returned from the
 *     cache. Otherwise the resource will be downloaded from the server and the cache will be updated.
 *   - If there is no match, the client will make a normal request, and will update the cache with
 *     the downloaded resource.
 *
 * - `no-store`: The client fetches the resource from the remote server without first looking in the
 *   cache, and will not update the cache with the downloaded resource.
 *
 * - `reload`: The client fetches the resource from the remote server without first looking in the
 *   cache, but then will update the cache with the downloaded resource.
 *
 * - `no-cache`: The client looks in its HTTP cache for a response matching the request.
 *   - If there is a match, fresh or stale, the client will make a conditional request to the remote
 *     server. If the server indicates that the resource has not changed, it will be returned from the
 *     cache. Otherwise the resource will be downloaded from the server and the cache will be updated.
 *   - If there is no match, the client will make a normal request, and will update the cache with
 *     the downloaded resource.
 *
 * - `force-cache`: The client looks in its HTTP cache for a response matching the request.
 *   - If there is a match, fresh or stale, it will be returned from the cache.
 *   - If there is no match, the client will make a normal request, and will update the cache with
 *     the downloaded resource.
 *
 * - `only-if-cached`: The client looks in its HTTP cache for a response matching the request.
 *   - If there is a match, fresh or stale, it will be returned from the cache.
 *   - If there is no match, a network error is returned.
 *
 * - `ignore-rules`: Custom to Faith. Overrides the check that determines if a response can be cached
 *   to always return true on 200. Uses any response in the HTTP cache matching the request, not
 *   paying attention to staleness. If there was no response, it creates a normal request and updates
 *   the HTTP cache with the response.
 */
export declare const enum CacheMode {
  Default = 'default',
  ForceCache = 'force-cache',
  IgnoreRules = 'ignore-rules',
  NoCache = 'no-cache',
  NoStore = 'no-store',
  OnlyIfCached = 'only-if-cached',
  Reload = 'reload'
}

export declare const enum CacheStore {
  Disk = 'disk',
  Memory = 'memory'
}

export interface ConnectionInfo {
  connectionType: string
  localAddress: string
  localPort: number
  remoteAddress: string
  remotePort: number
  firstSeen?: Date
  lastSeen?: Date
  expiry?: Date
  responseCount: number
  rttUs?: number
  rttVarUs?: number
  lostPackets?: number
  retransmits?: number
  totalRetransmits?: number
  congestionWindow?: number
  deliveryRateBps?: number
}

/**
 * Create a paired StreamBody and StreamBodySender for streaming request bodies.
 *
 * Usage:
 * ```js
 * const { body, sender } = createStreamBodyPair();
 * // Start the fetch with the body
 * const responsePromise = fetch(url, { method: 'POST', body, duplex: 'half' });
 * // Push chunks asynchronously
 * await sender.push(Buffer.from('chunk1'));
 * await sender.push(Buffer.from('chunk2'));
 * // Close when done
 * sender.close();
 * // Wait for response
 * const response = await responsePromise;
 * ```
 */
export declare function createStreamBodyPair(bufferSize?: number | undefined | null): { body: StreamBody, sender: StreamBodySender }

/**
 * Controls whether or not the client sends credentials with the request, as well as whether any
 * `Set-Cookie` response headers are respected. Credentials are cookies, ~~TLS client certificates,~~
 * or authentication headers containing a username and password. This option may be any one of the
 * following values:
 *
 * - `omit`: Never send credentials in the request or include credentials in the response.
 * - ~~`same-origin`~~: Faith does not implement this, as there is no concept of "origin" on the server.
 * - `include`: Always include credentials, ~~even for cross-origin requests.~~
 *
 * Faith ignores the `Access-Control-Allow-Credentials` and `Access-Control-Allow-Origin` headers.
 *
 * Faith currently does not `omit` the TLS client certificate when the request's `Agent` has one
 * configured. This is an upstream limitation.
 *
 * If the request's `Agent` has cookies enabled, new cookies from the response will be added to the
 * cookie jar, even as Faith strips them from the request and response headers returned to the user.
 * This is an upstream limitation.
 *
 * Defaults to `include` (browsers default to `same-origin`).
 */
export declare const enum CredentialsOption {
  Omit = 'omit',
  SameOrigin = 'same-origin',
  Include = 'include'
}

export interface DnsOverride {
  domain: string
  addresses: Array<string>
}

/**
 * Declares the duplex behaviour of the request. If this is present it must have the value `half`,
 * which is the only value the fetch standard defines.
 *
 * This option must be present when `body` is a `ReadableStream`.
 *
 * Faith does not act on the value: every request runs full duplex, so the response is available
 * as soon as its headers arrive, even while the request body is still being sent. `half` is a
 * token the standard obliges every streaming upload to carry rather than a preference, so
 * honouring it would strand code written against runtimes that also run full duplex.
 */
export declare const enum DuplexOption {
  Half = 'half'
}

export declare function errorCodes(): Array<string>

export const FAITH_VERSION: string

/**
 * Faith produces fine-grained errors, but maps them to a few javascript error types for fetch
 * compatibility. The `.code` property on errors thrown from Faith is set to a stable name for each
 * error kind, documented in this comprehensive mapping:
 *
 * - JS `AbortError`:
 *   - `Aborted` — request was aborted using `signal`
 *   - `Timeout` — request timed out
 * - JS `NetworkError`:
 *   - `Network` — network error
 *   - `Redirect` — when the agent is configured to error on redirects
 *   - `ContentLengthOverrun` — a body written with `response.toFile()` exceeded the advertised `Content-Length`
 * - JS `SyntaxError`:
 *   - `AddressParse` — IP parse error for `AgentOptions.dns.overrides`
 *   - `InvalidIntegrity` — SRI parse error for `RequestInit.integrity`
 *   - `JsonParse` — JSON parse error for `response.json()`
 *   - `PemParse` — PEM parse error for `AgentOptions.tls.identity` or `AgentOptions.tls.extraRoots`
 * - JS `TypeError`:
 *   - `Closed` — a request was made on an agent that has been closed
 *   - `InvalidHeader` — invalid header name or value
 *   - `InvalidMethod` — invalid HTTP method
 *   - `InvalidPath` — a `response.toFile()` destination that does not name a local path
 *   - `InvalidUrl` — invalid URL string
 *   - `ResponseAlreadyDisturbed` — body already read (mutually exclusive operations)
 *   - `ResponseBodyNull` — `response.toFile()` on a response that cannot carry a body
 * - JS generic `Error`:
 *   - `BodyStream` — internal stream handling error
 *   - `Config` — invalid agent configuration
 *   - `FileExists` — a `response.toFile()` write refusing an occupied destination
 *   - `FileWrite` — the filesystem refusing a `response.toFile()` write
 *   - `IntegrityMismatch` — SRI checksum mismatch (with `RequestInit.integrity`)
 *
 * The library exports an `ERROR_CODES` object which has every error code the library throws, and
 * every error thrown also has a `code` property that is set to one of those codes. So you can
 * accurately respond to the exact error kind by checking its code and matching against the right
 * constant from `ERROR_CODES`, instead of doing string matching on the error message, or coarse
 * `instance of` matching.
 *
 * Due to technical limitations, when reading a body stream, reads might fail, but that error
 * will not have a `code` property.
 */
export declare const enum FaithErrorKind {
  Aborted = 'Aborted',
  AddressParse = 'AddressParse',
  BodyStream = 'BodyStream',
  Closed = 'Closed',
  Config = 'Config',
  ContentLengthOverrun = 'ContentLengthOverrun',
  FileExists = 'FileExists',
  FileWrite = 'FileWrite',
  IntegrityMismatch = 'IntegrityMismatch',
  InvalidHeader = 'InvalidHeader',
  InvalidIntegrity = 'InvalidIntegrity',
  InvalidMethod = 'InvalidMethod',
  InvalidPath = 'InvalidPath',
  InvalidUrl = 'InvalidUrl',
  JsonParse = 'JsonParse',
  Network = 'Network',
  PemParse = 'PemParse',
  Redirect = 'Redirect',
  ResponseAlreadyDisturbed = 'ResponseAlreadyDisturbed',
  ResponseBodyNull = 'ResponseBodyNull',
  Timeout = 'Timeout'
}

export declare function faithFetch(url: string, options: FaithOptionsAndBody, signal?: AbortSignal | undefined | null, streamBody?: StreamBody | undefined | null): Promise<FaithResponse>

export interface FaithOptionsAndBody {
  agent: Agent
  body?: string | Buffer | Uint8Array
  cache?: CacheMode
  credentials?: CredentialsOption
  duplex?: DuplexOption
  headers?: Array<[string, string]>
  integrity?: string
  method?: string
  /**
   * The relative priority of this request: `high`, `low`, or `auto`.
   *
   * Taken as a string rather than an enum so that an unrecognised value is ignored like any
   * other option Faith does not recognise, rather than rejected.
   */
  priority?: string
  timeout?: number
}

/**
 * Sets the default headers for every request.
 *
 * If header names or values are invalid, they are silently omitted.
 * Sensitive headers (e.g. `Authorization`) should be marked.
 *
 * Default: none.
 */
export interface Header {
  name: string
  value: string
  sensitive?: boolean
}

export declare const enum Http3Congestion {
  Cubic = 'cubic',
  Bbr1 = 'bbr1'
}

/**
 * A hint that HTTP/3 is available at a specific host and port. This pre-populates the Alt-Svc
 * cache so the first request to this host will attempt HTTP/3 immediately.
 */
export interface Http3Hint {
  /** The hostname (e.g., "example.com"). */
  host: string
  /** The port number (e.g., 443). */
  port: number
}

/**
 * Determines the behavior in case the server replies with a redirect status.
 * One of the following values:
 *
 * - `follow`: automatically follow redirects. Faith limits this to 10 redirects.
 * - `error`: reject the promise with a network error when a redirect status is returned.
 * - ~~`manual`~~: not supported.
 * - `stop`: (Faith custom) don't follow any redirects, return the responses.
 *
 * Defaults to `follow`.
 */
export declare const enum Redirect {
  Follow = 'follow',
  Error = 'error',
  Manual = 'manual',
  Stop = 'stop'
}

export const REQWEST_VERSION: string

/** One entry of `Agent.resolvers()`: a DNS server the agent resolves through (spec:OBS#resolvers). */
export interface ResolverInfo {
  /** The server's address, as `ip:port`. */
  address: string
  /** The transport in use: `udp`, `tcp`, `tls`, `https`, `quic`, or `h3`. */
  transport: string
  /** How the transport was arrived at: `configured` by the caller, or `conventional` DNS. */
  source: string
}

/**
 * The measurements behind a response's timing breakdown.
 *
 * The wrapper turns these into a `PerformanceResourceTiming`; the phases are milliseconds from
 * the start of the request rather than absolute times, so the wrapper can place them on the
 * same clock as the rest of the platform's performance entries.
 */
export interface TimingBreakdown {
  headersMs: number
  bodyMs?: number
  reused: boolean
  nextHopProtocol: string
  contentEncoding?: string
  fromCache: boolean
}

/** Options for `toFile()`. */
export interface ToFileOptions {
  /**
   * Whether to truncate and replace an occupied destination. Defaults to false, which
   * refuses an occupied destination with a `FileExists` error and leaves it untouched.
   */
  overwrite?: boolean
  /**
   * The permissions a newly created file is given, defaulting to what Node's own
   * filesystem writes use. Ignored on platforms without Unix file modes.
   */
  mode?: number
}

/** A progress report from a `toFile()` write in flight. */
export interface ToFileProgress {
  /** The number of bytes written to the file so far. */
  bytesWritten: number
  /**
   * What the response advertised in `Content-Length`, when it sent one and Faith is
   * not decoding the body. Absent when the total is not known ahead of time, which is
   * the case for a chunked response and for one Faith decodes.
   */
  contentLength?: number
}

/** What `toFile()` resolves to. */
export interface ToFileResult {
  /** The absolute filesystem path written to. */
  path: string
  /** The number of bytes that landed at the destination. */
  bytesWritten: number
}

/**
 * Custom user agent string.
 *
 * Default: `Faith/{version} reqwest/{version}`.
 *
 * You may use the `USER_AGENT` constant if you wish to prepend your own agent to the default, e.g.
 *
 * ```javascript
 * import { Agent, USER_AGENT } from '@passcod/faith';
 * const agent = new Agent({
 *   userAgent: `YourApp/1.2.3 ${USER_AGENT}`,
 * });
 * ```
 */
export const USER_AGENT: string
