[package]
name = "web-faith-alt-svc"
description = "An HTTP/3 upgrade (via Alt-Svc primarily) mechanism for reqwest"
version = "1.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/web-faith-alt-svc"
authors.workspace = true

[dependencies]
async-trait.workspace = true
http.workspace = true
moka.workspace = true
reqwest.workspace = true
reqwest-middleware.workspace = true
tokio.workspace = true
url.workspace = true
web-faith-dns = { workspace = true, optional = true }

[dev-dependencies]
http.workspace = true
reqwest.workspace = true
tokio = { workspace = true }

[features]
default = ["dns"]
dns = ["dep:web-faith-dns"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
