[package]
name = "web-faith-encoding"
description = "HTTP content coding for request and response bodies"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/web-faith-encoding"
authors.workspace = true

[dependencies]
async-compression.workspace = true
bytes.workspace = true
futures.workspace = true
http.workspace = true
tokio.workspace = true
tokio-util.workspace = true
