[package]
name = "web-faith-cookies"
description = "A cookie jar for HTTP clients, specialised for the server-side context"
version = "1.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/web-faith-cookies"
authors.workspace = true

[dependencies]
cookie.workspace = true
cookie_store.workspace = true
http.workspace = true
time.workspace = true
url.workspace = true
reqwest = { workspace = true, optional = true }

[dev-dependencies]
http.workspace = true
url.workspace = true

[features]
reqwest = ["dep:reqwest", "reqwest/cookies"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
